---
name: Render README.md

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - '.github/scripts/render_readme.py'
    - 'templates/README.md.j2'
    - 'data.json'

jobs:
  render-readme:
    runs-on: ubuntu-20.04
    steps:
    - name: Get k8s-at-home token
      id: get-app-token
      uses: getsentry/action-github-app-token@v1
      with:
        app_id: ${{ secrets.K8S_AT_HOME_APP_ID }}
        private_key: ${{ secrets.K8S_AT_HOME_APP_PRIVATE_KEY }}

    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ steps.get-app-token.outputs.token }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r .github/scripts/requirements.txt

    - name: Run script
      id: run
      run: |
        python .github/scripts/render_readme.py > README.md

    - name: Create commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        push_options: --force
        commit_message: Auto-generate README
        commit_user_name: k8s-at-home[bot]
        commit_user_email: k8s-at-home[bot]@users.noreply.github.com
        commit_author: k8s-at-home[bot] <k8s-at-home[bot]@users.noreply.github.com>
        file_pattern: README.md
